### ISSUE TITLE
FHIR specs

### ISSUE THREAD

**Issue by cyberjanus** [adkendall/DHPDocs#3]
We need to expand the documentation to include the FHIR profiles which developers ultimately need to call the APIs.

**Comment by adkendall** [comment]
Appointments service FHIR Implementation section added. @cyberjanus and @johnatggc  please have a look and let me know any thoughts on format, style etc. In the meantime I'll start on the other services in the same format.

Issues I know about:
Text wrapping - created issue here for this https://github.com/adkendall/DHPDocs/issues/4
Linking - I wanted to link to the Appointments Business Service but couldn't get it working quickly so gave up for now
Forge Screenshots - Not sure I like using those for various reasons but have left them in for now.
Examples - No examples at present but these can be populated and improved upon as we move forward - hopefully the dev team can contribute also

**Comment by cyberjanus** [comment]
Added text to the business services to explain where to find the FHIR profiles.

**Comment by adkendall** [comment]
I think we are in OK shape now for a first release. The API docs are now live and can be maintained as we move forward so I'll close this issue. Re-open if you disagree @cyberjanus  @johnatggc
