### ISSUE TITLE
Table text wrapping

### ISSUE THREAD

**Issue by adkendall** [adkendall/DHPDocs#4]
Text within table cells doesn't seem to wrap properly. 

Could be same issue as

https://stackoverflow.com/questions/16570087/multiple-lines-of-text-in-single-cell-of-simple-table 

and

https://rackerlabs.github.io/docs-rackspace/tools/rtd-tables.html

**Comment by johnatggc** [comment]
Fix found here: https://github.com/rtfd/sphinx_rtd_theme/issues/117
Added _static\table_wrap_override.css and updated conf.py

**Comment by adkendall** [comment]
Looks OK now so closing this issue.
