### ISSUE TITLE
Query: Have the contained resources in the ECSMedicalRecord Composition changed at all?

### ISSUE THREAD

**Issue by cyberjanus** [adkendall/DHPDocs#5]
I wrote the Health & Care Information Service on the assumption that the detail inside the composition sections is still the same.
@adkendall , could you please double check that the business service description is still correct?

**Comment by adkendall** [comment]
@cyberjanus - No it is still the same - the only thing that has recently changed is the profile declaration 
 on the Composition (https://digitalhealthplatform.scot/fhir/DhpEcsMedicalRecord) but the contained resources are still either MedicationStatement or AllergyIntolerence.

**Comment by adkendall** [comment]
@cyberjanus  - Are you happy to close this issue?

**Comment by cyberjanus** [comment]
happy to close. We'll need to talk separately about the thinking behind setting the service up as Health Information Service when the structure is still tied to ECS as the feeder system.
